# https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/
# https://rancher.com/docs/rancher/v2.5/en/k8s-in-rancher/horitzontal-pod-autoscaler/testing-hpa/
# https://docs.oracle.com/pt-br/iaas/Content/ContEng/Tasks/contengusinghorizontalpodautoscaler.htm
#apiVersion: autoscaling/v2beta1
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-clientes
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 10
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 50
  #- type: Pods
  #  pods:
  #    metric:
  #      name: packets-per-second
  #      target:
  #        type: AverageValue
  #        averageValue: 1
  #- type: Object
  #  object:
  #    metric:
  #      name: http_requests
  #      selector: {matchLabels: {verb: GET}}       
  #      target:
  #        type: AverageValue
  #        averageValue: 1
