apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
 name: vpa-clientes
spec:
 targetRef:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
 updatePolicy:
 updateMode: "initial"
 #updateMode: "Auto"
