kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
    name: portworx-storageclass
provisioner: kubernetes.io/portworx-volume
parameters:
   repl: "3"
   io_profile: "db"
   fs: "xfs"
allowVolumeExpansion: true
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
   name: mongo-pvc
   annotations:
     volume.beta.kubernetes.io/storage-class: portworx-storageclass
spec:
   accessModes:
     - ReadWriteOnce
   resources:
     requests:
       storage: 5Gi
